name: my_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you are publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.3
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.1.0
  sign_in_with_apple: ^6.1.1
  async: ^2.8.2
  fluttertoast: ^8.2.1
  connectivity_plus: ^6.0.3
  font_awesome_flutter: ^10.3.0
  cloud_firestore: ^5.0.2
  battery_plus: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
